### ISSUE TITLE
Tracer Summarise failed when plotting reconstructed lengths

### ISSUE THREAD

**Issue by mn120110d** [Teichlab/tracer#40] opened 2017-05-31 10:00 UTC
Hi Mike,

We wanted to test TraCeR with files from the link: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE45428. There are provided three samples: Jurkat Cells 216, 236 and 245. The samples are provided in SRA format, so we used SRA Toolkit Fastq-Dump available here: https://github.com/ncbi/sra-tools for generating fastq files for these paired end reads. First, we ran TraCeR Assemble for fastq files generated for Jurkat Cells 216. In attachment you can find the results of the assemble phase. Than we tried to run TraCeR Summarise, but we got an exception on line sns.distplot() in file tasks.py. Here is also the output of the program that produced this error:
[Tracer Summarise dump.txt](https://github.com/Teichlab/tracer/files/1040978/Tracer.Summarise.dump.txt)

When we commented the line sns.distplot() in tasks.py, the program executed fine. Is it possible for you to handle this exception in the code, so the program can continue with further execution without plotting reconstructed lengths?

Thank you!
Tamara and Nevena

Results of the assemble phase: (Species set to Hsap for both assemble and summarise)
[cell_line_216.zip](https://github.com/Teichlab/tracer/files/1040960/cell_line_216.zip)

**Comment by boombard** [comment] 2017-05-31 10:26
Hi

I can't reproduce your error with your assembly output. I think it may be a problem that was resolved in an update of the seaborn library, when there is only one point for a kde plot.

Could you tell me which version of seaborn you currently have installed with `pip show seaborn`? And how have you installed tracer?

Here are the figures that created the error you are seeing:

[reconstructed_lengths_TCR_A.pdf](https://github.com/Teichlab/tracer/files/1041069/reconstructed_lengths_TCR_A.pdf)
[reconstructed_lengths_TCR_B.pdf](https://github.com/Teichlab/tracer/files/1041070/reconstructed_lengths_TCR_B.pdf)

**Comment by mn120110d** [comment] 2017-06-01 07:58
Hi,

We found the solution to this problem. It turned out that we didn't have installed statsmodels. Now that we have installed it, we get the expected output. Thank you for your help!

**Closed** 2017-06-01 09:46 UTC
